<script src="<?php echo e(asset('customer-assets/js/vendor/modernizr-3.11.2.min.js')); ?>"></script>
<script src="<?php echo e(asset('customer-assets/js/vendor/jquery-3.7.1.min.js')); ?>"></script>
<script src="<?php echo e(asset('customer-assets/js/vendor/bootstrap.bundle-5.3.2.min.js')); ?>"></script>
<script src="<?php echo e(asset('customer-assets/js/plugin/swiper/swiper-bundle.min.js')); ?>"></script>
<script src="<?php echo e(asset('customer-assets/js/plugin/countdown/countdown.js')); ?>"></script>
<script src="<?php echo e(asset('customer-assets/js/plugin/vanilla-tilt/vanilla-tilt.min.js')); ?>"></script>
<script src="<?php echo e(asset('customer-assets/js/plugin/rasta-contact/script.js')); ?>"></script>
<script src="<?php echo e(asset('customer-assets/js/plugin/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js')); ?>"></script>
<script src="<?php echo e(asset('customer-assets/js/plugins.js')); ?>"></script>
<script src="<?php echo e(asset('customer-assets/js/main.js')); ?>"></script>
<script src="<?php echo e(asset ('customer-assets/js/plugin/otp-sms/otp-input.js')); ?>"></script>
<script src="<?php echo e(asset ('customer-assets/js/plugin/otp-loader/script.js')); ?>"></script><?php /**PATH C:\Users\saleh\Desktop\amanj perfume\resources\views/customer/layouts/script.blade.php ENDPATH**/ ?>